In [2]:
import numpy as np
data = np.array(np.random.randint(0, 7, size=25)).reshape(5,5)
print(data)
data[[1,3]] = data[[3,1]]
# data

[[6 3 4 1 4]
 [0 5 3 5 5]
 [3 3 0 5 3]
 [5 1 0 3 4]
 [1 2 4 2 1]]


In [ ]:
import numpy as np
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))

# print(normalized_data)

In [ ]:
import numpy as np
z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)

In [ ]:
import numpy as np
splitted = np.ravel(data)
groups = np.split(splitted, 5)
print(groups)

In [ ]:
import numpy as np
vector1 = np.array([3,5,6,7,8])
vector2 = np.array([2,4,6,8,10])

dot = np.dot(vector1, vector2)
print(dot)

In [ ]:
import numpy as np
data2 = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

print(data * data2)

In [ ]:
import numpy as np
identity3 = np.identity(3) * 2
print(identity3)

inverse = identity3 * data2

In [ ]:
import numpy as np
eigenvalues, eigenvectors = np.linalg.eig(data)

In [4]:
import numpy as np
nan_indices = np.random.randint(0,5, size=(5,2))
for index in nan_indices:
   data[index[0], index[1]] = np.nan_to_num(np.nan)

print(np.where(np.isnan(data)))

mean = np.nanmean(data)
data[np.isnan(data)] = mean

(array([], dtype=int64), array([], dtype=int64))
