In [3]:
import numpy as np

In [4]:
# create a vector array of zeroes size 10
zeroes = np.zeros(10)
# print(zeroes)

In [ ]:
# compute memory size of array
numpy_arr = np.array([1,2,3,4,5])
size = numpy_arr.itemsize * len(numpy_arr)
# print(size)

In [ ]:
# retrieve add function documentation from cli
# np.info(np.add)

In [ ]:
# vector array from 10 to 49
list = np.arange(10, 50)
# print(list)
# reverse a vector
reversed_list = list[::-1]
# print(reversed_list)

In [ ]:
# 3*3 matrix from 0 to 8 using reshape
matrix = np.reshape(np.arange(0,9), (3,3))
# print(matrix)

# find non zero elements
array = np.array([1,2,0,0,4,0])
non_zeroes = np.nonzero(array)
# print(non_zeroes)

# 3*3 matrix 
matrix = np.eye(3)
# print(matrix)

# 5*5 matrix where each row contains 1-4
matrix = np.tile(np.arange(5), (5,1))
# print(matrix)

# vector size 10 ranging from 0 to 1
matrix = np.linspace(0,1,10)
# print(matrix)

# create vector size 10 and sort it
atrix = np.random.rand(10)
matrix = np.sort(matrix)
# print(matrix)


In [ ]:
# min and max for each type

print("Min:", np.iinfo(np.int8).min)
print("Max:", np.iinfo(np.int8).max)
print()


print("int32:")
print("Min:", np.iinfo(np.int32).min)
print("Max:", np.iinfo(np.int32).max)
print()


print("int64:")
print("Min:", np.iinfo(np.int64).min)
print("Max:", np.iinfo(np.int64).max)
print()

# Floating-point types

print("float32:")
print("Min:", np.finfo(np.float32).min)
print("Max:", np.finfo(np.float32).max)
print()


print("float64:")
print("Min:", np.finfo(np.float64).min)
print("Max:", np.finfo(np.float64).max)
print()

# convert float array to integer array

In [7]:
import numpy as np
# convert 32 bit float vector to int vector
array  = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
conversion =  array.astype(np.int32)
conversion


array([1, 2, 3, 4, 5], dtype=int32)

In [11]:
import numpy as np
# subtract mean from each row
matrix = np.array([[1,2,9], [4,5,6]])
changed = matrix - np.mean(matrix, axis=1, keepdims=True)
changed

array([[-3., -2.,  5.],
       [-1.,  0.,  1.]])

In [13]:
import numpy as np
# sort an array on nth column
matrix = np.array([[1,2,3], [4,5,6], [-1, 4, 1]])
sorted = np.argsort(matrix[:,2])
sorted_matrix = matrix[sorted]
sorted_matrix

array([[-1,  4,  1],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [14]:
import numpy as np
# swap two rows
matrix = np.reshape(np.arange(0,9), (3,3))

matrix[[0,1]] = matrix[[1,0]]
matrix

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [16]:
# Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.
import numpy as np
c = np.array([3,2,1,4])
print(c)
a = np.repeat(np.arange(len(c)), c)
print(a)
print(np.bincount(a) == c)

[3 2 1 4]
[0 0 0 1 1 2 3 3 3 3]
[ True  True  True  True]
